version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword  
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]  
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  eurekaserver:
    build:
      context: ./eurekaServer
    container_name: eurekaserver
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  apigateway:
    build:
      context: ./mainGateway
    container_name: apigateway
    depends_on:
      - eurekaserver
      - bookstorageservice
      - booktrackerservice
      - authenticationservice
    environment:
      SPRING_APPLICATION_NAME: apigateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_MVC_TIMEZONE: Europe/Moscow
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  bookstorageservice:
    build:
      context: ./bookStorageService
    container_name: bookstorageservice
    depends_on:
      - mysql-db
      - eurekaserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/library?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword  
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_APPLICATION_NAME: bookstorageservice
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8082:8082"
    networks:
      - mynetwork

  booktrackerservice:
    build:
      context: ./bookTrackerService
    container_name: booktrackerservice
    depends_on:
      - mysql-db
      - eurekaserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/library?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword  
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_APPLICATION_NAME: booktrackerservice
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8083:8083"
    networks:
      - mynetwork

  authenticationservice:
    build:
      context: ./authenticationService
    container_name: authenticationservice
    depends_on:
      - mysql-db
      - eurekaserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/library?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword  
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_APPLICATION_NAME: authenticationservice
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8081:8081"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
